# See list of built-in substitutions at
# https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values
substitutions:
  _GCLOUD_PROJECT: gdg-devfest-auburn
  _CLOUDSDK_COMPUTE_ZONE: us-central1-b
  _CLOUDSDK_CONTAINER_CLUSTER: dev-cluster
  _REPO_NAME: gdg-devfest-auburn

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/${_REPO_NAME}:latest
  - -t
  - gcr.io/$PROJECT_ID/${_REPO_NAME}:$COMMIT_SHA
  - --cache-from
  - gcr.io/$PROJECT_ID/${_REPO_NAME}:latest
  - .
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/${_REPO_NAME}:$COMMIT_SHA
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - apply
    - -f
    - kubernetes.yaml
  env:
  - 'GCLOUD_PROJECT=${_GCLOUD_PROJECT}'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'

images: [
  'gcr.io/$PROJECT_ID/${_REPO_NAME}:latest'
]

timeout: 1200s

tags:
- ${_REPO_NAME}
