apiVersion: apps/v1
kind: Deployment
metadata:
  name: dig-deployment
  labels:
    app: dig
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dig
  template:
    metadata:
      labels:
        app: dig
    spec:
      containers:
      - name: dig
        image: dig
        ports:
          - containerPort: 8080
            name: http
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#        livenessProbe:
#          httpGet:
#            path: /healthcheck
#            port: 80
